// GENERATED — do not edit by hand. ISO-3166 alpha-2 country names +
// continent grouping, generated from Node Intl.DisplayNames to match the
// web SDK's lib/regions.ts (which uses the browser Intl.DisplayNames).

const Map<String, String> kCountryNames = {
  'DZ': "Algeria",
  'AO': "Angola",
  'BJ': "Benin",
  'BW': "Botswana",
  'BF': "Burkina Faso",
  'BI': "Burundi",
  'CV': "Cape Verde",
  'CM': "Cameroon",
  'CF': "Central African Republic",
  'TD': "Chad",
  'KM': "Comoros",
  'CG': "Congo - Brazzaville",
  'CD': "Congo - Kinshasa",
  'CI': "Côte d’Ivoire",
  'DJ': "Djibouti",
  'EG': "Egypt",
  'GQ': "Equatorial Guinea",
  'ER': "Eritrea",
  'SZ': "Eswatini",
  'ET': "Ethiopia",
  'GA': "Gabon",
  'GM': "Gambia",
  'GH': "Ghana",
  'GN': "Guinea",
  'GW': "Guinea-Bissau",
  'KE': "Kenya",
  'LS': "Lesotho",
  'LR': "Liberia",
  'LY': "Libya",
  'MG': "Madagascar",
  'MW': "Malawi",
  'ML': "Mali",
  'MR': "Mauritania",
  'MU': "Mauritius",
  'YT': "Mayotte",
  'MA': "Morocco",
  'MZ': "Mozambique",
  'NA': "Namibia",
  'NE': "Niger",
  'NG': "Nigeria",
  'RE': "Réunion",
  'RW': "Rwanda",
  'SH': "St. Helena",
  'ST': "São Tomé & Príncipe",
  'SN': "Senegal",
  'SC': "Seychelles",
  'SL': "Sierra Leone",
  'SO': "Somalia",
  'ZA': "South Africa",
  'SS': "South Sudan",
  'SD': "Sudan",
  'TZ': "Tanzania",
  'TG': "Togo",
  'TN': "Tunisia",
  'UG': "Uganda",
  'EH': "Western Sahara",
  'ZM': "Zambia",
  'ZW': "Zimbabwe",
  'AE': "United Arab Emirates",
  'BH': "Bahrain",
  'IL': "Israel",
  'IQ': "Iraq",
  'IR': "Iran",
  'JO': "Jordan",
  'KW': "Kuwait",
  'LB': "Lebanon",
  'OM': "Oman",
  'PS': "Palestinian Territories",
  'QA': "Qatar",
  'SA': "Saudi Arabia",
  'SY': "Syria",
  'TR': "Türkiye",
  'YE': "Yemen",
  'AD': "Andorra",
  'AL': "Albania",
  'AT': "Austria",
  'AX': "Åland Islands",
  'BA': "Bosnia & Herzegovina",
  'BE': "Belgium",
  'BG': "Bulgaria",
  'BY': "Belarus",
  'CH': "Switzerland",
  'CY': "Cyprus",
  'CZ': "Czechia",
  'DE': "Germany",
  'DK': "Denmark",
  'EE': "Estonia",
  'ES': "Spain",
  'FI': "Finland",
  'FO': "Faroe Islands",
  'FR': "France",
  'GB': "United Kingdom",
  'GG': "Guernsey",
  'GI': "Gibraltar",
  'GR': "Greece",
  'HR': "Croatia",
  'HU': "Hungary",
  'IE': "Ireland",
  'IM': "Isle of Man",
  'IS': "Iceland",
  'IT': "Italy",
  'JE': "Jersey",
  'LI': "Liechtenstein",
  'LT': "Lithuania",
  'LU': "Luxembourg",
  'LV': "Latvia",
  'MC': "Monaco",
  'MD': "Moldova",
  'ME': "Montenegro",
  'MK': "North Macedonia",
  'MT': "Malta",
  'NL': "Netherlands",
  'NO': "Norway",
  'PL': "Poland",
  'PT': "Portugal",
  'RO': "Romania",
  'RS': "Serbia",
  'RU': "Russia",
  'SE': "Sweden",
  'SI': "Slovenia",
  'SJ': "Svalbard & Jan Mayen",
  'SK': "Slovakia",
  'SM': "San Marino",
  'UA': "Ukraine",
  'VA': "Vatican City",
  'XK': "Kosovo",
  'AG': "Antigua & Barbuda",
  'AI': "Anguilla",
  'AR': "Argentina",
  'AW': "Aruba",
  'BB': "Barbados",
  'BL': "St. Barthélemy",
  'BM': "Bermuda",
  'BO': "Bolivia",
  'BQ': "Caribbean Netherlands",
  'BR': "Brazil",
  'BS': "Bahamas",
  'BZ': "Belize",
  'CA': "Canada",
  'CL': "Chile",
  'CO': "Colombia",
  'CR': "Costa Rica",
  'CU': "Cuba",
  'CW': "Curaçao",
  'DM': "Dominica",
  'DO': "Dominican Republic",
  'EC': "Ecuador",
  'FK': "Falkland Islands",
  'GD': "Grenada",
  'GF': "French Guiana",
  'GL': "Greenland",
  'GP': "Guadeloupe",
  'GT': "Guatemala",
  'GY': "Guyana",
  'HN': "Honduras",
  'HT': "Haiti",
  'JM': "Jamaica",
  'KN': "St. Kitts & Nevis",
  'KY': "Cayman Islands",
  'LC': "St. Lucia",
  'MF': "St. Martin",
  'MQ': "Martinique",
  'MS': "Montserrat",
  'MX': "Mexico",
  'NI': "Nicaragua",
  'PA': "Panama",
  'PE': "Peru",
  'PM': "St. Pierre & Miquelon",
  'PR': "Puerto Rico",
  'PY': "Paraguay",
  'SR': "Suriname",
  'SV': "El Salvador",
  'SX': "Sint Maarten",
  'TC': "Turks & Caicos Islands",
  'TT': "Trinidad & Tobago",
  'US': "United States",
  'UY': "Uruguay",
  'VC': "St. Vincent & Grenadines",
  'VE': "Venezuela",
  'VG': "British Virgin Islands",
  'VI': "U.S. Virgin Islands",
  'AF': "Afghanistan",
  'AM': "Armenia",
  'AS': "American Samoa",
  'AU': "Australia",
  'AZ': "Azerbaijan",
  'BD': "Bangladesh",
  'BN': "Brunei",
  'BT': "Bhutan",
  'CK': "Cook Islands",
  'CN': "China",
  'FJ': "Fiji",
  'FM': "Micronesia",
  'GE': "Georgia",
  'GU': "Guam",
  'HK': "Hong Kong SAR China",
  'ID': "Indonesia",
  'IN': "India",
  'JP': "Japan",
  'KG': "Kyrgyzstan",
  'KH': "Cambodia",
  'KI': "Kiribati",
  'KP': "North Korea",
  'KR': "South Korea",
  'KZ': "Kazakhstan",
  'LA': "Laos",
  'LK': "Sri Lanka",
  'MH': "Marshall Islands",
  'MM': "Myanmar (Burma)",
  'MN': "Mongolia",
  'MO': "Macao SAR China",
  'MP': "Northern Mariana Islands",
  'MV': "Maldives",
  'MY': "Malaysia",
  'NC': "New Caledonia",
  'NF': "Norfolk Island",
  'NP': "Nepal",
  'NR': "Nauru",
  'NU': "Niue",
  'NZ': "New Zealand",
  'PF': "French Polynesia",
  'PG': "Papua New Guinea",
  'PH': "Philippines",
  'PK': "Pakistan",
  'PN': "Pitcairn Islands",
  'PW': "Palau",
  'SB': "Solomon Islands",
  'SG': "Singapore",
  'TH': "Thailand",
  'TJ': "Tajikistan",
  'TK': "Tokelau",
  'TL': "Timor-Leste",
  'TM': "Turkmenistan",
  'TO': "Tonga",
  'TV': "Tuvalu",
  'TW': "Taiwan",
  'UZ': "Uzbekistan",
  'VN': "Vietnam",
  'VU': "Vanuatu",
  'WF': "Wallis & Futuna",
  'WS': "Samoa",
};

const Map<String, String> kRegionByCode = {
  'DZ': 'Africa',
  'AO': 'Africa',
  'BJ': 'Africa',
  'BW': 'Africa',
  'BF': 'Africa',
  'BI': 'Africa',
  'CV': 'Africa',
  'CM': 'Africa',
  'CF': 'Africa',
  'TD': 'Africa',
  'KM': 'Africa',
  'CG': 'Africa',
  'CD': 'Africa',
  'CI': 'Africa',
  'DJ': 'Africa',
  'EG': 'Africa',
  'GQ': 'Africa',
  'ER': 'Africa',
  'SZ': 'Africa',
  'ET': 'Africa',
  'GA': 'Africa',
  'GM': 'Africa',
  'GH': 'Africa',
  'GN': 'Africa',
  'GW': 'Africa',
  'KE': 'Africa',
  'LS': 'Africa',
  'LR': 'Africa',
  'LY': 'Africa',
  'MG': 'Africa',
  'MW': 'Africa',
  'ML': 'Africa',
  'MR': 'Africa',
  'MU': 'Africa',
  'YT': 'Africa',
  'MA': 'Africa',
  'MZ': 'Africa',
  'NA': 'Africa',
  'NE': 'Africa',
  'NG': 'Africa',
  'RE': 'Africa',
  'RW': 'Africa',
  'SH': 'Africa',
  'ST': 'Africa',
  'SN': 'Africa',
  'SC': 'Africa',
  'SL': 'Africa',
  'SO': 'Africa',
  'ZA': 'Africa',
  'SS': 'Africa',
  'SD': 'Africa',
  'TZ': 'Africa',
  'TG': 'Africa',
  'TN': 'Africa',
  'UG': 'Africa',
  'EH': 'Africa',
  'ZM': 'Africa',
  'ZW': 'Africa',
  'AE': 'Middle East',
  'BH': 'Middle East',
  'IL': 'Middle East',
  'IQ': 'Middle East',
  'IR': 'Middle East',
  'JO': 'Middle East',
  'KW': 'Middle East',
  'LB': 'Middle East',
  'OM': 'Middle East',
  'PS': 'Middle East',
  'QA': 'Middle East',
  'SA': 'Middle East',
  'SY': 'Middle East',
  'TR': 'Middle East',
  'YE': 'Middle East',
  'AD': 'Europe',
  'AL': 'Europe',
  'AT': 'Europe',
  'AX': 'Europe',
  'BA': 'Europe',
  'BE': 'Europe',
  'BG': 'Europe',
  'BY': 'Europe',
  'CH': 'Europe',
  'CY': 'Europe',
  'CZ': 'Europe',
  'DE': 'Europe',
  'DK': 'Europe',
  'EE': 'Europe',
  'ES': 'Europe',
  'FI': 'Europe',
  'FO': 'Europe',
  'FR': 'Europe',
  'GB': 'Europe',
  'GG': 'Europe',
  'GI': 'Europe',
  'GR': 'Europe',
  'HR': 'Europe',
  'HU': 'Europe',
  'IE': 'Europe',
  'IM': 'Europe',
  'IS': 'Europe',
  'IT': 'Europe',
  'JE': 'Europe',
  'LI': 'Europe',
  'LT': 'Europe',
  'LU': 'Europe',
  'LV': 'Europe',
  'MC': 'Europe',
  'MD': 'Europe',
  'ME': 'Europe',
  'MK': 'Europe',
  'MT': 'Europe',
  'NL': 'Europe',
  'NO': 'Europe',
  'PL': 'Europe',
  'PT': 'Europe',
  'RO': 'Europe',
  'RS': 'Europe',
  'RU': 'Europe',
  'SE': 'Europe',
  'SI': 'Europe',
  'SJ': 'Europe',
  'SK': 'Europe',
  'SM': 'Europe',
  'UA': 'Europe',
  'VA': 'Europe',
  'XK': 'Europe',
  'AG': 'Americas',
  'AI': 'Americas',
  'AR': 'Americas',
  'AW': 'Americas',
  'BB': 'Americas',
  'BL': 'Americas',
  'BM': 'Americas',
  'BO': 'Americas',
  'BQ': 'Americas',
  'BR': 'Americas',
  'BS': 'Americas',
  'BZ': 'Americas',
  'CA': 'Americas',
  'CL': 'Americas',
  'CO': 'Americas',
  'CR': 'Americas',
  'CU': 'Americas',
  'CW': 'Americas',
  'DM': 'Americas',
  'DO': 'Americas',
  'EC': 'Americas',
  'FK': 'Americas',
  'GD': 'Americas',
  'GF': 'Americas',
  'GL': 'Americas',
  'GP': 'Americas',
  'GT': 'Americas',
  'GY': 'Americas',
  'HN': 'Americas',
  'HT': 'Americas',
  'JM': 'Americas',
  'KN': 'Americas',
  'KY': 'Americas',
  'LC': 'Americas',
  'MF': 'Americas',
  'MQ': 'Americas',
  'MS': 'Americas',
  'MX': 'Americas',
  'NI': 'Americas',
  'PA': 'Americas',
  'PE': 'Americas',
  'PM': 'Americas',
  'PR': 'Americas',
  'PY': 'Americas',
  'SR': 'Americas',
  'SV': 'Americas',
  'SX': 'Americas',
  'TC': 'Americas',
  'TT': 'Americas',
  'US': 'Americas',
  'UY': 'Americas',
  'VC': 'Americas',
  'VE': 'Americas',
  'VG': 'Americas',
  'VI': 'Americas',
  'AF': 'Asia & Pacific',
  'AM': 'Asia & Pacific',
  'AS': 'Asia & Pacific',
  'AU': 'Asia & Pacific',
  'AZ': 'Asia & Pacific',
  'BD': 'Asia & Pacific',
  'BN': 'Asia & Pacific',
  'BT': 'Asia & Pacific',
  'CK': 'Asia & Pacific',
  'CN': 'Asia & Pacific',
  'FJ': 'Asia & Pacific',
  'FM': 'Asia & Pacific',
  'GE': 'Asia & Pacific',
  'GU': 'Asia & Pacific',
  'HK': 'Asia & Pacific',
  'ID': 'Asia & Pacific',
  'IN': 'Asia & Pacific',
  'JP': 'Asia & Pacific',
  'KG': 'Asia & Pacific',
  'KH': 'Asia & Pacific',
  'KI': 'Asia & Pacific',
  'KP': 'Asia & Pacific',
  'KR': 'Asia & Pacific',
  'KZ': 'Asia & Pacific',
  'LA': 'Asia & Pacific',
  'LK': 'Asia & Pacific',
  'MH': 'Asia & Pacific',
  'MM': 'Asia & Pacific',
  'MN': 'Asia & Pacific',
  'MO': 'Asia & Pacific',
  'MP': 'Asia & Pacific',
  'MV': 'Asia & Pacific',
  'MY': 'Asia & Pacific',
  'NC': 'Asia & Pacific',
  'NF': 'Asia & Pacific',
  'NP': 'Asia & Pacific',
  'NR': 'Asia & Pacific',
  'NU': 'Asia & Pacific',
  'NZ': 'Asia & Pacific',
  'PF': 'Asia & Pacific',
  'PG': 'Asia & Pacific',
  'PH': 'Asia & Pacific',
  'PK': 'Asia & Pacific',
  'PN': 'Asia & Pacific',
  'PW': 'Asia & Pacific',
  'SB': 'Asia & Pacific',
  'SG': 'Asia & Pacific',
  'TH': 'Asia & Pacific',
  'TJ': 'Asia & Pacific',
  'TK': 'Asia & Pacific',
  'TL': 'Asia & Pacific',
  'TM': 'Asia & Pacific',
  'TO': 'Asia & Pacific',
  'TV': 'Asia & Pacific',
  'TW': 'Asia & Pacific',
  'UZ': 'Asia & Pacific',
  'VN': 'Asia & Pacific',
  'VU': 'Asia & Pacific',
  'WF': 'Asia & Pacific',
  'WS': 'Asia & Pacific',
};
